name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)
        echo "DOCKER_HOST=$DOCKER_HOST" >> $GITHUB_ENV
        echo "DOCKER_TLS_VERIFY=$DOCKER_TLS_VERIFY" >> $GITHUB_ENV
        echo "DOCKER_CERT_PATH=$DOCKER_CERT_PATH" >> $GITHUB_ENV
    
    - name: Build Backend Docker image
      run: |
        cd backend
        docker build -t abdulahadmalik/attendance-backend:latest .
    
    - name: Build Frontend Docker image
      run: |
        cd frontend
        docker build -t abdulahadmalik/attendance-frontend:latest .
    
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Push Backend image to Docker Hub
      run: docker push abdulahadmalik/attendance-backend:latest
    
    - name: Push Frontend image to Docker Hub
      run: docker push abdulahadmalik/attendance-frontend:latest
    
    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        
    - name: Wait for Deployment
      run: |
        kubectl rollout status deployment/attendance-backend
        kubectl rollout status deployment/attendance-frontend
        
    - name: Verify Deployment
      run: |
        echo "Pods Status:"
        kubectl get pods
        echo "Services Status:"
        kubectl get services